const names = [{
  "id": 1,
  "first_name": "Lorrie",
  "last_name": "Rameaux",
  "email": "lrameaux0@japanpost.jp",
  "gender": "Female"
}, {
  "id": 2,
  "first_name": "Skipp",
  "last_name": "Vasin",
  "email": "svasin1@feedburner.com",
  "gender": "Male"
}, {
  "id": 3,
  "first_name": "Batholomew",
  "last_name": "Antrum",
  "email": "bantrum2@sciencedaily.com",
  "gender": "Male"
}, {
  "id": 4,
  "first_name": "Hunter",
  "last_name": "Colquite",
  "email": "hcolquite3@jalbum.net",
  "gender": "Male"
}, {
  "id": 5,
  "first_name": "Doro",
  "last_name": "MacVay",
  "email": "dmacvay4@tuttocitta.it",
  "gender": "Female"
}, {
  "id": 6,
  "first_name": "Marie-jeanne",
  "last_name": "Clayson",
  "email": "mclayson5@skype.com",
  "gender": "Female"
}, {
  "id": 7,
  "first_name": "Lanita",
  "last_name": "Arnoldi",
  "email": "larnoldi6@time.com",
  "gender": "Female"
}, {
  "id": 8,
  "first_name": "Fredia",
  "last_name": "Browncey",
  "email": "fbrowncey7@com.com",
  "gender": "Female"
}, {
  "id": 9,
  "first_name": "Isac",
  "last_name": "Dobel",
  "email": "idobel8@deliciousdays.com",
  "gender": "Male"
}, {
  "id": 10,
  "first_name": "Yank",
  "last_name": "Kitching",
  "email": "ykitching9@i2i.jp",
  "gender": "Male"
}, {
  "id": 11,
  "first_name": "Alix",
  "last_name": "Easterby",
  "email": "aeasterbya@yandex.ru",
  "gender": "Male"
}, {
  "id": 12,
  "first_name": "Darby",
  "last_name": "Chasemore",
  "email": "dchasemoreb@google.co.uk",
  "gender": "Female"
}, {
  "id": 13,
  "first_name": "Cornall",
  "last_name": "Riding",
  "email": "cridingc@domainmarket.com",
  "gender": "Male"
}, {
  "id": 14,
  "first_name": "Donnell",
  "last_name": "Mallia",
  "email": "dmalliad@artisteer.com",
  "gender": "Male"
}, {
  "id": 15,
  "first_name": "Michaeline",
  "last_name": "Claypoole",
  "email": "mclaypoolee@comcast.net",
  "gender": "Female"
}]

export default names
